# Generated by Django 4.0.1 on 2022-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('nick_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('civil_status', models.CharField(max_length=30)),
                ('purok', models.CharField(max_length=30)),
                ('voter_status', models.CharField(max_length=30)),
            ],
        ),
    ]
