# Generated by Django 4.0.1 on 2022-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0002_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant', models.CharField(max_length=30)),
                ('respondent', models.CharField(max_length=30)),
                ('victim', models.CharField(max_length=30)),
                ('types', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=30)),
            ],
        ),
    ]
